language: rust
sudo: false

# we you unstable issues and need Rust nightly
# however we of course hope that we will be able to use stable at some point
rust:
  - nightly

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# compile, test all, benchmark and create documentation
script:
  - |
      travis-cargo build &&
      travis-cargo test --features slow_test &&
      travis-cargo bench &&
      travis-cargo doc
  
env:
  global:
    # override the default `--features unstable` used for the nightly branch which would make the build fail
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - RUSTC="$TRAVIS_BUILD_DIR/rustc.sh"