language: rust
sudo: false

# we you unstable issues and need Rust nightly
# however we of course hope that we will be able to use stable at some point
rust:
  - nightly

# compile, test all, benchmark and create documentation
script:
  - |
      cargo build &&
      cargo test --features slow_test &&
      cargo bench &&
      cargo doc
  
env:
  global:
    # Add certain compiler flags with the rustc wrapper script
    - RUSTC="$TRAVIS_BUILD_DIR/rustc.sh"