[package]
name = "basic_dsp"
version = "0.2.0"
authors = ["Christian Liebhardt"]
license = "MIT" # num_cpus prevents an Apache2 license
homepage = "https://github.com/liebharc/basic_dsp"
repository = "https://github.com/liebharc/basic_dsp"
documentation = "https://liebharc.github.io/basic_dsp/basic_dsp/"
keywords = ["dsp", "digital signal processing"]
description = """
Digital signal processing based on 1xN (one times N) or Nx1 vectors in real or complex number space.
Vectors come with basic arithmetic, convolution, Fourier transformation and interpolation operations.
"""

[profile.dev]
codegen-units = 4

[profile.test]
codegen-units = 4

[lib]
name = "basic_dsp"
crate-type = ["dylib", "rlib"]

[features]
slow_test = []

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"
[dev-dependencies.rand]
rand = "^0.3.12"
[dependencies]
simd = { git = "https://github.com/rekka/simd.git", branch="avx" }
num_cpus = "^0.2.10"
simple_parallel = "^0.3.0"
num = "^0.1.30"
rustfft = "^1.0.0"