[package]
name = "basic_dsp"
version = "0.1.0"
authors = ["Christian Liebhardt <christian.liebhardt@arcor.de>"]

[lib]
name = "basic_dsp"
crate-type = ["dylib", "rlib"]

[features]
slow_test = []

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"
[dev-dependencies.rand]
rand = "*"
[dependencies]
simd = { git = "https://github.com/liebharc/simd" }
num_cpus = "*"
simple_parallel = "*"
num = "*"
rustfft = "*"

[[test]]
name = "test"
path = "tests/test.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"