[package]
name = "basic_dsp"
version = "0.2.3"
authors = ["Christian Liebhardt"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/liebharc/basic_dsp"
repository = "https://github.com/liebharc/basic_dsp"
documentation = "https://liebharc.github.io/basic_dsp/basic_dsp/"
keywords = ["dsp", "vector", "interpolation", "convolution"]
description = """
Digital signal processing based on 1xN (one times N) or Nx1 vectors in real or complex number space.
Vectors come with basic arithmetic, convolution, Fourier transformation and interpolation operations.
"""

[profile.dev]
codegen-units = 4

[profile.test]
codegen-units = 4

[lib]
name = "basic_dsp"
crate-type = ["dylib", "rlib"]

[features]
slow_test = []

[dependencies]
simd = "^0.1.1"
num_cpus = "^0.2.10"
crossbeam = "^0.2.0"
num = "^0.1.30"
rustfft = "^1.0.0"

[dev-dependencies]
hamcrest = "^0.1.0"
rand = "^0.3.12"
