[package]
name = "basic_dsp"
version = "0.1.1"
authors = ["Christian Liebhardt <christian.liebhardt@arcor.de>"]

[profile.dev]
codegen-units = 4

[profile.test]
codegen-units = 4

[lib]
name = "basic_dsp"
crate-type = ["dylib", "rlib"]

[features]
slow_test = []

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"
[dev-dependencies.rand]
rand = { git = "https://github.com/fhahn/rand.git", branch="fix-ind" }
[dependencies]
simd = { git = "https://github.com/rekka/simd.git", branch="avx" }
num_cpus = "*"
simple_parallel = "*"
num = "*"
rustfft = "*"

[[test]]
name = "test"
path = "tests/test.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"