[package]
name = "basic_dsp"
version = "0.1.0"
authors = ["Christian Liebhardt <christian.liebhardt@arcor.de>"]

[dev-dependencies.hamcrest]
git = "https://github.com/carllerche/hamcrest-rust.git"
[dependencies]
simd = { git = "https://github.com/huonw/simd" }
num_cpus = "0.2.6"
simple_parallel = "0.2.1"
num = "0.1.27"