[package]
name = "basic_dsp_vector"
version = "0.4.0"
authors = ["Christian Liebhardt"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/liebharc/basic_dsp"
repository = "https://github.com/liebharc/basic_dsp"
documentation = "https://liebharc.github.io/basic_dsp/basic_dsp/"
keywords = ["dsp", "vector", "interpolation", "convolution", "matrix"]
description = """
Digital signal processing based on real or complex vectors in time or frequency domain.
Vectors come with basic arithmetic, convolution, Fourier transformation and interpolation operations. The vectors are optimized for sizes of a couple of thousand elements or more.
"""

[profile.dev]
codegen-units = 4

[profile.test]
codegen-units = 4

[features]
use_avx = ["use_simd"]
use_sse = ["use_simd"]
use_simd = ["simd"]

[dependencies]
simd = { version = "^0.1.1", optional = true }
num_cpus = "^0.2.10"
crossbeam = "^0.2.0"
num = "^0.1.34"
rustfft = "^1.0.0"
